// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: tr451_vomci_sbi_service.proto

//**************************************************************************
// TR-451 vOMCI SBI Service Protocol Buffer Schema
//
//  Copyright (c) 2021, Broadband Forum
//
//  Redistribution and use in source and binary forms, with or
//   without modification, are permitted provided that the following
//   conditions are met:
//
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//
//   2. Redistributions in binary form must reproduce the above
//      copyright notice, this list of conditions and the following
//      disclaimer in the documentation and/or other materials
//      provided with the distribution.
//
//   3. Neither the name of the copyright holder nor the names of its
//      contributors may be used to endorse or promote products
//      derived from this software without specific prior written
//      permission.
//
//   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
//   CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
//   INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
//   DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
//   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
//   NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
//   CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
//   STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
//   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
//   ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
//   The above license is used as a license under copyright only.
//   Please reference the Forum IPR Policy for patent licensing terms
//   <https://www.broadband-forum.org/ipr-policy>.
//
//   Any moral rights which are necessary to exercise under the above
//   license grant are also deemed granted under this license.
//
// | Version           | Name                   | Date       |
// | TR-451 1.0.0      | vOMCI Specification    | TBD, 2021  |
//
// BBF software release registry: http://www.broadband-forum.org/software
//**************************************************************************

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_tr451_vomci_sbi_service_proto protoreflect.FileDescriptor

const file_tr451_vomci_sbi_service_proto_rawDesc = "" +
	"\n" +
	"\x1dtr451_vomci_sbi_service.proto\x12\x1atr451_vomci_sbi_service.v1\x1a\x1dtr451_vomci_sbi_message.proto\x1a\x1bgoogle/protobuf/empty.proto2|\n" +
	"\rVomciHelloSbi\x12k\n" +
	"\n" +
	"HelloVomci\x12-.tr451_vomci_sbi_message.v1.HelloVomciRequest\x1a..tr451_vomci_sbi_message.v1.HelloVomciResponse2\xb6\x01\n" +
	"\x0fVomciMessageSbi\x12V\n" +
	"\x10ListenForVomciRx\x12\x16.google.protobuf.Empty\x1a(.tr451_vomci_sbi_message.v1.VomciMessage0\x01\x12K\n" +
	"\aVomciTx\x12(.tr451_vomci_sbi_message.v1.VomciMessage\x1a\x16.google.protobuf.EmptyB\x03Z\x01.b\x06proto3"

var file_tr451_vomci_sbi_service_proto_goTypes = []any{
	(*HelloVomciRequest)(nil),  // 0: tr451_vomci_sbi_message.v1.HelloVomciRequest
	(*emptypb.Empty)(nil),      // 1: google.protobuf.Empty
	(*VomciMessage)(nil),       // 2: tr451_vomci_sbi_message.v1.VomciMessage
	(*HelloVomciResponse)(nil), // 3: tr451_vomci_sbi_message.v1.HelloVomciResponse
}
var file_tr451_vomci_sbi_service_proto_depIdxs = []int32{
	0, // 0: tr451_vomci_sbi_service.v1.VomciHelloSbi.HelloVomci:input_type -> tr451_vomci_sbi_message.v1.HelloVomciRequest
	1, // 1: tr451_vomci_sbi_service.v1.VomciMessageSbi.ListenForVomciRx:input_type -> google.protobuf.Empty
	2, // 2: tr451_vomci_sbi_service.v1.VomciMessageSbi.VomciTx:input_type -> tr451_vomci_sbi_message.v1.VomciMessage
	3, // 3: tr451_vomci_sbi_service.v1.VomciHelloSbi.HelloVomci:output_type -> tr451_vomci_sbi_message.v1.HelloVomciResponse
	2, // 4: tr451_vomci_sbi_service.v1.VomciMessageSbi.ListenForVomciRx:output_type -> tr451_vomci_sbi_message.v1.VomciMessage
	1, // 5: tr451_vomci_sbi_service.v1.VomciMessageSbi.VomciTx:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tr451_vomci_sbi_service_proto_init() }
func file_tr451_vomci_sbi_service_proto_init() {
	if File_tr451_vomci_sbi_service_proto != nil {
		return
	}
	file_tr451_vomci_sbi_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tr451_vomci_sbi_service_proto_rawDesc), len(file_tr451_vomci_sbi_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_tr451_vomci_sbi_service_proto_goTypes,
		DependencyIndexes: file_tr451_vomci_sbi_service_proto_depIdxs,
	}.Build()
	File_tr451_vomci_sbi_service_proto = out.File
	file_tr451_vomci_sbi_service_proto_goTypes = nil
	file_tr451_vomci_sbi_service_proto_depIdxs = nil
}
