// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: tr451_vomci_sbi_service.proto

//**************************************************************************
// TR-451 vOMCI SBI Service Protocol Buffer Schema
//
//  Copyright (c) 2021, Broadband Forum
//
//  Redistribution and use in source and binary forms, with or
//   without modification, are permitted provided that the following
//   conditions are met:
//
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//
//   2. Redistributions in binary form must reproduce the above
//      copyright notice, this list of conditions and the following
//      disclaimer in the documentation and/or other materials
//      provided with the distribution.
//
//   3. Neither the name of the copyright holder nor the names of its
//      contributors may be used to endorse or promote products
//      derived from this software without specific prior written
//      permission.
//
//   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
//   CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
//   INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
//   DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
//   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
//   NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
//   CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
//   STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
//   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
//   ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
//   The above license is used as a license under copyright only.
//   Please reference the Forum IPR Policy for patent licensing terms
//   <https://www.broadband-forum.org/ipr-policy>.
//
//   Any moral rights which are necessary to exercise under the above
//   license grant are also deemed granted under this license.
//
// | Version           | Name                   | Date       |
// | TR-451 1.0.0      | vOMCI Specification    | TBD, 2021  |
//
// BBF software release registry: http://www.broadband-forum.org/software
//**************************************************************************

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VomciHelloSbi_HelloVomci_FullMethodName = "/tr451_vomci_sbi_service.v1.VomciHelloSbi/HelloVomci"
)

// VomciHelloSbiClient is the client API for VomciHelloSbi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VomciHelloSbiClient interface {
	HelloVomci(ctx context.Context, in *HelloVomciRequest, opts ...grpc.CallOption) (*HelloVomciResponse, error)
}

type vomciHelloSbiClient struct {
	cc grpc.ClientConnInterface
}

func NewVomciHelloSbiClient(cc grpc.ClientConnInterface) VomciHelloSbiClient {
	return &vomciHelloSbiClient{cc}
}

func (c *vomciHelloSbiClient) HelloVomci(ctx context.Context, in *HelloVomciRequest, opts ...grpc.CallOption) (*HelloVomciResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloVomciResponse)
	err := c.cc.Invoke(ctx, VomciHelloSbi_HelloVomci_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VomciHelloSbiServer is the server API for VomciHelloSbi service.
// All implementations must embed UnimplementedVomciHelloSbiServer
// for forward compatibility.
type VomciHelloSbiServer interface {
	HelloVomci(context.Context, *HelloVomciRequest) (*HelloVomciResponse, error)
	mustEmbedUnimplementedVomciHelloSbiServer()
}

// UnimplementedVomciHelloSbiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVomciHelloSbiServer struct{}

func (UnimplementedVomciHelloSbiServer) HelloVomci(context.Context, *HelloVomciRequest) (*HelloVomciResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelloVomci not implemented")
}
func (UnimplementedVomciHelloSbiServer) mustEmbedUnimplementedVomciHelloSbiServer() {}
func (UnimplementedVomciHelloSbiServer) testEmbeddedByValue()                       {}

// UnsafeVomciHelloSbiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VomciHelloSbiServer will
// result in compilation errors.
type UnsafeVomciHelloSbiServer interface {
	mustEmbedUnimplementedVomciHelloSbiServer()
}

func RegisterVomciHelloSbiServer(s grpc.ServiceRegistrar, srv VomciHelloSbiServer) {
	// If the following call pancis, it indicates UnimplementedVomciHelloSbiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VomciHelloSbi_ServiceDesc, srv)
}

func _VomciHelloSbi_HelloVomci_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloVomciRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VomciHelloSbiServer).HelloVomci(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VomciHelloSbi_HelloVomci_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VomciHelloSbiServer).HelloVomci(ctx, req.(*HelloVomciRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VomciHelloSbi_ServiceDesc is the grpc.ServiceDesc for VomciHelloSbi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VomciHelloSbi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tr451_vomci_sbi_service.v1.VomciHelloSbi",
	HandlerType: (*VomciHelloSbiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloVomci",
			Handler:    _VomciHelloSbi_HelloVomci_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tr451_vomci_sbi_service.proto",
}

const (
	VomciMessageSbi_ListenForVomciRx_FullMethodName = "/tr451_vomci_sbi_service.v1.VomciMessageSbi/ListenForVomciRx"
	VomciMessageSbi_VomciTx_FullMethodName          = "/tr451_vomci_sbi_service.v1.VomciMessageSbi/VomciTx"
)

// VomciMessageSbiClient is the client API for VomciMessageSbi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VomciMessageSbiClient interface {
	ListenForVomciRx(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VomciMessage], error)
	VomciTx(ctx context.Context, in *VomciMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type vomciMessageSbiClient struct {
	cc grpc.ClientConnInterface
}

func NewVomciMessageSbiClient(cc grpc.ClientConnInterface) VomciMessageSbiClient {
	return &vomciMessageSbiClient{cc}
}

func (c *vomciMessageSbiClient) ListenForVomciRx(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VomciMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VomciMessageSbi_ServiceDesc.Streams[0], VomciMessageSbi_ListenForVomciRx_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, VomciMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VomciMessageSbi_ListenForVomciRxClient = grpc.ServerStreamingClient[VomciMessage]

func (c *vomciMessageSbiClient) VomciTx(ctx context.Context, in *VomciMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, VomciMessageSbi_VomciTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VomciMessageSbiServer is the server API for VomciMessageSbi service.
// All implementations must embed UnimplementedVomciMessageSbiServer
// for forward compatibility.
type VomciMessageSbiServer interface {
	ListenForVomciRx(*emptypb.Empty, grpc.ServerStreamingServer[VomciMessage]) error
	VomciTx(context.Context, *VomciMessage) (*emptypb.Empty, error)
	mustEmbedUnimplementedVomciMessageSbiServer()
}

// UnimplementedVomciMessageSbiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVomciMessageSbiServer struct{}

func (UnimplementedVomciMessageSbiServer) ListenForVomciRx(*emptypb.Empty, grpc.ServerStreamingServer[VomciMessage]) error {
	return status.Errorf(codes.Unimplemented, "method ListenForVomciRx not implemented")
}
func (UnimplementedVomciMessageSbiServer) VomciTx(context.Context, *VomciMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VomciTx not implemented")
}
func (UnimplementedVomciMessageSbiServer) mustEmbedUnimplementedVomciMessageSbiServer() {}
func (UnimplementedVomciMessageSbiServer) testEmbeddedByValue()                         {}

// UnsafeVomciMessageSbiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VomciMessageSbiServer will
// result in compilation errors.
type UnsafeVomciMessageSbiServer interface {
	mustEmbedUnimplementedVomciMessageSbiServer()
}

func RegisterVomciMessageSbiServer(s grpc.ServiceRegistrar, srv VomciMessageSbiServer) {
	// If the following call pancis, it indicates UnimplementedVomciMessageSbiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VomciMessageSbi_ServiceDesc, srv)
}

func _VomciMessageSbi_ListenForVomciRx_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VomciMessageSbiServer).ListenForVomciRx(m, &grpc.GenericServerStream[emptypb.Empty, VomciMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VomciMessageSbi_ListenForVomciRxServer = grpc.ServerStreamingServer[VomciMessage]

func _VomciMessageSbi_VomciTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VomciMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VomciMessageSbiServer).VomciTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VomciMessageSbi_VomciTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VomciMessageSbiServer).VomciTx(ctx, req.(*VomciMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// VomciMessageSbi_ServiceDesc is the grpc.ServiceDesc for VomciMessageSbi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VomciMessageSbi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tr451_vomci_sbi_service.v1.VomciMessageSbi",
	HandlerType: (*VomciMessageSbiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VomciTx",
			Handler:    _VomciMessageSbi_VomciTx_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListenForVomciRx",
			Handler:       _VomciMessageSbi_ListenForVomciRx_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tr451_vomci_sbi_service.proto",
}
