// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: tr451_vomci_sbi_message.proto

//**************************************************************************
// TR-451 vOMCI SBI Message Protocol Buffer Schema
//
//  Copyright (c) 2021, Broadband Forum
//
//  Redistribution and use in source and binary forms, with or
//   without modification, are permitted provided that the following
//   conditions are met:
//
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//
//   2. Redistributions in binary form must reproduce the above
//      copyright notice, this list of conditions and the following
//      disclaimer in the documentation and/or other materials
//      provided with the distribution.
//
//   3. Neither the name of the copyright holder nor the names of its
//      contributors may be used to endorse or promote products
//      derived from this software without specific prior written
//      permission.
//
//   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
//   CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
//   INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
//   DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
//   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
//   NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
//   CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
//   STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
//   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
//   ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
//   The above license is used as a license under copyright only.
//   Please reference the Forum IPR Policy for patent licensing terms
//   <https://www.broadband-forum.org/ipr-policy>.
//
//   Any moral rights which are necessary to exercise under the above
//   license grant are also deemed granted under this license.
//
// | Version           | Name                   | Date       |
// | TR-451 1.0.0      | vOMCI Specification    | TBD, 2021  |
//
// BBF software release registry: http://www.broadband-forum.org/software
//**************************************************************************

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VomciError_VomciErrorCode int32

const (
	VomciError_ERROR_GENERAL        VomciError_VomciErrorCode = 0
	VomciError_NO_ROUTE_TO_ONU      VomciError_VomciErrorCode = 1 //The entity does not know which remote endpoint to send the message to the ONU
	VomciError_NO_RESPONSE_FROM_ONU VomciError_VomciErrorCode = 2 //The entity did not receive an expected response for a request from the ONU
	VomciError_UNSUPPORTED_REQUEST  VomciError_VomciErrorCode = 3 //The entity does not support the request
)

// Enum value maps for VomciError_VomciErrorCode.
var (
	VomciError_VomciErrorCode_name = map[int32]string{
		0: "ERROR_GENERAL",
		1: "NO_ROUTE_TO_ONU",
		2: "NO_RESPONSE_FROM_ONU",
		3: "UNSUPPORTED_REQUEST",
	}
	VomciError_VomciErrorCode_value = map[string]int32{
		"ERROR_GENERAL":        0,
		"NO_ROUTE_TO_ONU":      1,
		"NO_RESPONSE_FROM_ONU": 2,
		"UNSUPPORTED_REQUEST":  3,
	}
)

func (x VomciError_VomciErrorCode) Enum() *VomciError_VomciErrorCode {
	p := new(VomciError_VomciErrorCode)
	*p = x
	return p
}

func (x VomciError_VomciErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VomciError_VomciErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_tr451_vomci_sbi_message_proto_enumTypes[0].Descriptor()
}

func (VomciError_VomciErrorCode) Type() protoreflect.EnumType {
	return &file_tr451_vomci_sbi_message_proto_enumTypes[0]
}

func (x VomciError_VomciErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VomciError_VomciErrorCode.Descriptor instead.
func (VomciError_VomciErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_tr451_vomci_sbi_message_proto_rawDescGZIP(), []int{4, 0}
}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointName  string                 `protobuf:"bytes,1,opt,name=endpoint_name,json=endpointName,proto3" json:"endpoint_name,omitempty"` //OLT, vOMCI Proxy or vOMCI function endpoint name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_tr451_vomci_sbi_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_tr451_vomci_sbi_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_tr451_vomci_sbi_message_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetEndpointName() string {
	if x != nil {
		return x.EndpointName
	}
	return ""
}

type HelloVomciRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	LocalEndpointHello *Hello                 `protobuf:"bytes,1,opt,name=local_endpoint_hello,json=localEndpointHello,proto3" json:"local_endpoint_hello,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HelloVomciRequest) Reset() {
	*x = HelloVomciRequest{}
	mi := &file_tr451_vomci_sbi_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloVomciRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloVomciRequest) ProtoMessage() {}

func (x *HelloVomciRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tr451_vomci_sbi_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloVomciRequest.ProtoReflect.Descriptor instead.
func (*HelloVomciRequest) Descriptor() ([]byte, []int) {
	return file_tr451_vomci_sbi_message_proto_rawDescGZIP(), []int{1}
}

func (x *HelloVomciRequest) GetLocalEndpointHello() *Hello {
	if x != nil {
		return x.LocalEndpointHello
	}
	return nil
}

type HelloVomciResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RemoteEndpointHello *Hello                 `protobuf:"bytes,1,opt,name=remote_endpoint_hello,json=remoteEndpointHello,proto3" json:"remote_endpoint_hello,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HelloVomciResponse) Reset() {
	*x = HelloVomciResponse{}
	mi := &file_tr451_vomci_sbi_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloVomciResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloVomciResponse) ProtoMessage() {}

func (x *HelloVomciResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tr451_vomci_sbi_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloVomciResponse.ProtoReflect.Descriptor instead.
func (*HelloVomciResponse) Descriptor() ([]byte, []int) {
	return file_tr451_vomci_sbi_message_proto_rawDescGZIP(), []int{2}
}

func (x *HelloVomciResponse) GetRemoteEndpointHello() *Hello {
	if x != nil {
		return x.RemoteEndpointHello
	}
	return nil
}

type VomciMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestPayloadId string                 `protobuf:"bytes,1,opt,name=request_payload_id,json=requestPayloadId,proto3" json:"request_payload_id,omitempty"` //Optional: The request payload identifier received from the vOLTMF by the vOMCI function.
	// Types that are valid to be assigned to Msg:
	//
	//	*VomciMessage_ErrorMsg
	//	*VomciMessage_OmciPacketMsg
	//	*VomciMessage_TodPacketMsg
	//	*VomciMessage_OltInfoMsg
	Msg           isVomciMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VomciMessage) Reset() {
	*x = VomciMessage{}
	mi := &file_tr451_vomci_sbi_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VomciMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VomciMessage) ProtoMessage() {}

func (x *VomciMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tr451_vomci_sbi_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VomciMessage.ProtoReflect.Descriptor instead.
func (*VomciMessage) Descriptor() ([]byte, []int) {
	return file_tr451_vomci_sbi_message_proto_rawDescGZIP(), []int{3}
}

func (x *VomciMessage) GetRequestPayloadId() string {
	if x != nil {
		return x.RequestPayloadId
	}
	return ""
}

func (x *VomciMessage) GetMsg() isVomciMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *VomciMessage) GetErrorMsg() *VomciError {
	if x != nil {
		if x, ok := x.Msg.(*VomciMessage_ErrorMsg); ok {
			return x.ErrorMsg
		}
	}
	return nil
}

func (x *VomciMessage) GetOmciPacketMsg() *OmciPacket {
	if x != nil {
		if x, ok := x.Msg.(*VomciMessage_OmciPacketMsg); ok {
			return x.OmciPacketMsg
		}
	}
	return nil
}

func (x *VomciMessage) GetTodPacketMsg() *OmciPacket {
	if x != nil {
		if x, ok := x.Msg.(*VomciMessage_TodPacketMsg); ok {
			return x.TodPacketMsg
		}
	}
	return nil
}

func (x *VomciMessage) GetOltInfoMsg() *OltInfoMessage {
	if x != nil {
		if x, ok := x.Msg.(*VomciMessage_OltInfoMsg); ok {
			return x.OltInfoMsg
		}
	}
	return nil
}

type isVomciMessage_Msg interface {
	isVomciMessage_Msg()
}

type VomciMessage_ErrorMsg struct {
	ErrorMsg *VomciError `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3,oneof"`
}

type VomciMessage_OmciPacketMsg struct {
	OmciPacketMsg *OmciPacket `protobuf:"bytes,3,opt,name=omci_packet_msg,json=omciPacketMsg,proto3,oneof"`
}

type VomciMessage_TodPacketMsg struct {
	TodPacketMsg *OmciPacket `protobuf:"bytes,4,opt,name=tod_packet_msg,json=todPacketMsg,proto3,oneof"`
}

type VomciMessage_OltInfoMsg struct {
	OltInfoMsg *OltInfoMessage `protobuf:"bytes,5,opt,name=olt_info_msg,json=oltInfoMsg,proto3,oneof"`
}

func (*VomciMessage_ErrorMsg) isVomciMessage_Msg() {}

func (*VomciMessage_OmciPacketMsg) isVomciMessage_Msg() {}

func (*VomciMessage_TodPacketMsg) isVomciMessage_Msg() {}

func (*VomciMessage_OltInfoMsg) isVomciMessage_Msg() {}

type VomciError struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	ErrorCode        VomciError_VomciErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=tr451_vomci_sbi_message.v1.VomciError_VomciErrorCode" json:"error_code,omitempty"`
	ErrorDescription string                    `protobuf:"bytes,2,opt,name=error_description,json=errorDescription,proto3" json:"error_description,omitempty"` //Optional: Error description
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VomciError) Reset() {
	*x = VomciError{}
	mi := &file_tr451_vomci_sbi_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VomciError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VomciError) ProtoMessage() {}

func (x *VomciError) ProtoReflect() protoreflect.Message {
	mi := &file_tr451_vomci_sbi_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VomciError.ProtoReflect.Descriptor instead.
func (*VomciError) Descriptor() ([]byte, []int) {
	return file_tr451_vomci_sbi_message_proto_rawDescGZIP(), []int{4}
}

func (x *VomciError) GetErrorCode() VomciError_VomciErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return VomciError_ERROR_GENERAL
}

func (x *VomciError) GetErrorDescription() string {
	if x != nil {
		return x.ErrorDescription
	}
	return ""
}

type OnuHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OltName       string                 `protobuf:"bytes,1,opt,name=olt_name,json=oltName,proto3" json:"olt_name,omitempty"`                  //The OLT name
	ChnlTermName  string                 `protobuf:"bytes,2,opt,name=chnl_term_name,json=chnlTermName,proto3" json:"chnl_term_name,omitempty"` //The reference identifier to the channel termination of the TR-385 vANI
	OnuId         uint32                 `protobuf:"varint,3,opt,name=onu_id,json=onuId,proto3" json:"onu_id,omitempty"`                       //The TC layer ONU-ID identifier of the TR-385 vANI
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnuHeader) Reset() {
	*x = OnuHeader{}
	mi := &file_tr451_vomci_sbi_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnuHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnuHeader) ProtoMessage() {}

func (x *OnuHeader) ProtoReflect() protoreflect.Message {
	mi := &file_tr451_vomci_sbi_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnuHeader.ProtoReflect.Descriptor instead.
func (*OnuHeader) Descriptor() ([]byte, []int) {
	return file_tr451_vomci_sbi_message_proto_rawDescGZIP(), []int{5}
}

func (x *OnuHeader) GetOltName() string {
	if x != nil {
		return x.OltName
	}
	return ""
}

func (x *OnuHeader) GetChnlTermName() string {
	if x != nil {
		return x.ChnlTermName
	}
	return ""
}

func (x *OnuHeader) GetOnuId() uint32 {
	if x != nil {
		return x.OnuId
	}
	return 0
}

type OmciMsgRetrans struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TMaxi         uint32                 `protobuf:"varint,1,opt,name=t_maxi,json=tMaxi,proto3" json:"t_maxi,omitempty"` //Optional: The maximum threshold value, in milliseconds, for timer expiration as defined in ITU-T G.988/B.2. A value of 0 indicates that the field is not defined.
	RMaxi         uint32                 `protobuf:"varint,2,opt,name=r_maxi,json=rMaxi,proto3" json:"r_maxi,omitempty"` //Optional: The maximum retries associated with this message as defined in ITU-T G.988/B.2 plus 1 (e.g., Value 1 is the first retry) A value of 0 indicates that the field is not defined.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OmciMsgRetrans) Reset() {
	*x = OmciMsgRetrans{}
	mi := &file_tr451_vomci_sbi_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OmciMsgRetrans) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OmciMsgRetrans) ProtoMessage() {}

func (x *OmciMsgRetrans) ProtoReflect() protoreflect.Message {
	mi := &file_tr451_vomci_sbi_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OmciMsgRetrans.ProtoReflect.Descriptor instead.
func (*OmciMsgRetrans) Descriptor() ([]byte, []int) {
	return file_tr451_vomci_sbi_message_proto_rawDescGZIP(), []int{6}
}

func (x *OmciMsgRetrans) GetTMaxi() uint32 {
	if x != nil {
		return x.TMaxi
	}
	return 0
}

func (x *OmciMsgRetrans) GetRMaxi() uint32 {
	if x != nil {
		return x.RMaxi
	}
	return 0
}

type MessageInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OmciMsgRetrans *OmciMsgRetrans        `protobuf:"bytes,1,opt,name=omci_msg_retrans,json=omciMsgRetrans,proto3" json:"omci_msg_retrans,omitempty"` //Optional: OMCI message retransmission applied
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageInfo) Reset() {
	*x = MessageInfo{}
	mi := &file_tr451_vomci_sbi_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageInfo) ProtoMessage() {}

func (x *MessageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tr451_vomci_sbi_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageInfo.ProtoReflect.Descriptor instead.
func (*MessageInfo) Descriptor() ([]byte, []int) {
	return file_tr451_vomci_sbi_message_proto_rawDescGZIP(), []int{7}
}

func (x *MessageInfo) GetOmciMsgRetrans() *OmciMsgRetrans {
	if x != nil {
		return x.OmciMsgRetrans
	}
	return nil
}

type OmciPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *OnuHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	MsgInfo       *MessageInfo           `protobuf:"bytes,2,opt,name=msg_info,json=msgInfo,proto3" json:"msg_info,omitempty"` //Optional: Message information
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                //OMCI message payload without the CRC/MIC
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OmciPacket) Reset() {
	*x = OmciPacket{}
	mi := &file_tr451_vomci_sbi_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OmciPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OmciPacket) ProtoMessage() {}

func (x *OmciPacket) ProtoReflect() protoreflect.Message {
	mi := &file_tr451_vomci_sbi_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OmciPacket.ProtoReflect.Descriptor instead.
func (*OmciPacket) Descriptor() ([]byte, []int) {
	return file_tr451_vomci_sbi_message_proto_rawDescGZIP(), []int{8}
}

func (x *OmciPacket) GetHeader() *OnuHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *OmciPacket) GetMsgInfo() *MessageInfo {
	if x != nil {
		return x.MsgInfo
	}
	return nil
}

func (x *OmciPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type OltInfoMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*OltInfoMessage_OltOnuInfoReq
	//	*OltInfoMessage_OltOnuInfoRsp
	Msg           isOltInfoMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OltInfoMessage) Reset() {
	*x = OltInfoMessage{}
	mi := &file_tr451_vomci_sbi_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OltInfoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OltInfoMessage) ProtoMessage() {}

func (x *OltInfoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tr451_vomci_sbi_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OltInfoMessage.ProtoReflect.Descriptor instead.
func (*OltInfoMessage) Descriptor() ([]byte, []int) {
	return file_tr451_vomci_sbi_message_proto_rawDescGZIP(), []int{9}
}

func (x *OltInfoMessage) GetMsg() isOltInfoMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *OltInfoMessage) GetOltOnuInfoReq() *OltOnuInfoReq {
	if x != nil {
		if x, ok := x.Msg.(*OltInfoMessage_OltOnuInfoReq); ok {
			return x.OltOnuInfoReq
		}
	}
	return nil
}

func (x *OltInfoMessage) GetOltOnuInfoRsp() *OltOnuInfoRsp {
	if x != nil {
		if x, ok := x.Msg.(*OltInfoMessage_OltOnuInfoRsp); ok {
			return x.OltOnuInfoRsp
		}
	}
	return nil
}

type isOltInfoMessage_Msg interface {
	isOltInfoMessage_Msg()
}

type OltInfoMessage_OltOnuInfoReq struct {
	OltOnuInfoReq *OltOnuInfoReq `protobuf:"bytes,1,opt,name=olt_onu_info_req,json=oltOnuInfoReq,proto3,oneof"`
}

type OltInfoMessage_OltOnuInfoRsp struct {
	OltOnuInfoRsp *OltOnuInfoRsp `protobuf:"bytes,2,opt,name=olt_onu_info_rsp,json=oltOnuInfoRsp,proto3,oneof"`
}

func (*OltInfoMessage_OltOnuInfoReq) isOltInfoMessage_Msg() {}

func (*OltInfoMessage_OltOnuInfoRsp) isOltInfoMessage_Msg() {}

type OltOnuInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *OnuHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` //OLT information is scoped toward a specific ONU
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OltOnuInfoReq) Reset() {
	*x = OltOnuInfoReq{}
	mi := &file_tr451_vomci_sbi_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OltOnuInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OltOnuInfoReq) ProtoMessage() {}

func (x *OltOnuInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_tr451_vomci_sbi_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OltOnuInfoReq.ProtoReflect.Descriptor instead.
func (*OltOnuInfoReq) Descriptor() ([]byte, []int) {
	return file_tr451_vomci_sbi_message_proto_rawDescGZIP(), []int{10}
}

func (x *OltOnuInfoReq) GetHeader() *OnuHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type OltOnuInfoRsp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Header           *OnuHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                                //OLT information is scoped toward a specific ONU
	GemSuperframeSeq uint32                 `protobuf:"varint,2,opt,name=gem_superframe_seq,json=gemSuperframeSeq,proto3" json:"gem_superframe_seq,omitempty"` //The sequence number of the specified GEM superframe as defined in the OLT-G ME in ITU-T G.988
	Tstampn          string                 `protobuf:"bytes,3,opt,name=tstampn,proto3" json:"tstampn,omitempty"`                                              //The TstampN as defined in the OLT-G ME in ITU-T G.988
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OltOnuInfoRsp) Reset() {
	*x = OltOnuInfoRsp{}
	mi := &file_tr451_vomci_sbi_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OltOnuInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OltOnuInfoRsp) ProtoMessage() {}

func (x *OltOnuInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_tr451_vomci_sbi_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OltOnuInfoRsp.ProtoReflect.Descriptor instead.
func (*OltOnuInfoRsp) Descriptor() ([]byte, []int) {
	return file_tr451_vomci_sbi_message_proto_rawDescGZIP(), []int{11}
}

func (x *OltOnuInfoRsp) GetHeader() *OnuHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *OltOnuInfoRsp) GetGemSuperframeSeq() uint32 {
	if x != nil {
		return x.GemSuperframeSeq
	}
	return 0
}

func (x *OltOnuInfoRsp) GetTstampn() string {
	if x != nil {
		return x.Tstampn
	}
	return ""
}

var File_tr451_vomci_sbi_message_proto protoreflect.FileDescriptor

const file_tr451_vomci_sbi_message_proto_rawDesc = "" +
	"\n" +
	"\x1dtr451_vomci_sbi_message.proto\x12\x1atr451_vomci_sbi_message.v1\",\n" +
	"\x05Hello\x12#\n" +
	"\rendpoint_name\x18\x01 \x01(\tR\fendpointName\"h\n" +
	"\x11HelloVomciRequest\x12S\n" +
	"\x14local_endpoint_hello\x18\x01 \x01(\v2!.tr451_vomci_sbi_message.v1.HelloR\x12localEndpointHello\"k\n" +
	"\x12HelloVomciResponse\x12U\n" +
	"\x15remote_endpoint_hello\x18\x01 \x01(\v2!.tr451_vomci_sbi_message.v1.HelloR\x13remoteEndpointHello\"\xfc\x02\n" +
	"\fVomciMessage\x12,\n" +
	"\x12request_payload_id\x18\x01 \x01(\tR\x10requestPayloadId\x12E\n" +
	"\terror_msg\x18\x02 \x01(\v2&.tr451_vomci_sbi_message.v1.VomciErrorH\x00R\berrorMsg\x12P\n" +
	"\x0fomci_packet_msg\x18\x03 \x01(\v2&.tr451_vomci_sbi_message.v1.OmciPacketH\x00R\romciPacketMsg\x12N\n" +
	"\x0etod_packet_msg\x18\x04 \x01(\v2&.tr451_vomci_sbi_message.v1.OmciPacketH\x00R\ftodPacketMsg\x12N\n" +
	"\folt_info_msg\x18\x05 \x01(\v2*.tr451_vomci_sbi_message.v1.OltInfoMessageH\x00R\n" +
	"oltInfoMsgB\x05\n" +
	"\x03msg\"\xfc\x01\n" +
	"\n" +
	"VomciError\x12T\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e25.tr451_vomci_sbi_message.v1.VomciError.VomciErrorCodeR\terrorCode\x12+\n" +
	"\x11error_description\x18\x02 \x01(\tR\x10errorDescription\"k\n" +
	"\x0eVomciErrorCode\x12\x11\n" +
	"\rERROR_GENERAL\x10\x00\x12\x13\n" +
	"\x0fNO_ROUTE_TO_ONU\x10\x01\x12\x18\n" +
	"\x14NO_RESPONSE_FROM_ONU\x10\x02\x12\x17\n" +
	"\x13UNSUPPORTED_REQUEST\x10\x03\"c\n" +
	"\tOnuHeader\x12\x19\n" +
	"\bolt_name\x18\x01 \x01(\tR\aoltName\x12$\n" +
	"\x0echnl_term_name\x18\x02 \x01(\tR\fchnlTermName\x12\x15\n" +
	"\x06onu_id\x18\x03 \x01(\rR\x05onuId\">\n" +
	"\x0eOmciMsgRetrans\x12\x15\n" +
	"\x06t_maxi\x18\x01 \x01(\rR\x05tMaxi\x12\x15\n" +
	"\x06r_maxi\x18\x02 \x01(\rR\x05rMaxi\"c\n" +
	"\vMessageInfo\x12T\n" +
	"\x10omci_msg_retrans\x18\x01 \x01(\v2*.tr451_vomci_sbi_message.v1.OmciMsgRetransR\x0eomciMsgRetrans\"\xa9\x01\n" +
	"\n" +
	"OmciPacket\x12=\n" +
	"\x06header\x18\x01 \x01(\v2%.tr451_vomci_sbi_message.v1.OnuHeaderR\x06header\x12B\n" +
	"\bmsg_info\x18\x02 \x01(\v2'.tr451_vomci_sbi_message.v1.MessageInfoR\amsgInfo\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\xc3\x01\n" +
	"\x0eOltInfoMessage\x12T\n" +
	"\x10olt_onu_info_req\x18\x01 \x01(\v2).tr451_vomci_sbi_message.v1.OltOnuInfoReqH\x00R\roltOnuInfoReq\x12T\n" +
	"\x10olt_onu_info_rsp\x18\x02 \x01(\v2).tr451_vomci_sbi_message.v1.OltOnuInfoRspH\x00R\roltOnuInfoRspB\x05\n" +
	"\x03msg\"N\n" +
	"\rOltOnuInfoReq\x12=\n" +
	"\x06header\x18\x01 \x01(\v2%.tr451_vomci_sbi_message.v1.OnuHeaderR\x06header\"\x96\x01\n" +
	"\rOltOnuInfoRsp\x12=\n" +
	"\x06header\x18\x01 \x01(\v2%.tr451_vomci_sbi_message.v1.OnuHeaderR\x06header\x12,\n" +
	"\x12gem_superframe_seq\x18\x02 \x01(\rR\x10gemSuperframeSeq\x12\x18\n" +
	"\atstampn\x18\x03 \x01(\tR\atstampnB\x03Z\x01.b\x06proto3"

var (
	file_tr451_vomci_sbi_message_proto_rawDescOnce sync.Once
	file_tr451_vomci_sbi_message_proto_rawDescData []byte
)

func file_tr451_vomci_sbi_message_proto_rawDescGZIP() []byte {
	file_tr451_vomci_sbi_message_proto_rawDescOnce.Do(func() {
		file_tr451_vomci_sbi_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tr451_vomci_sbi_message_proto_rawDesc), len(file_tr451_vomci_sbi_message_proto_rawDesc)))
	})
	return file_tr451_vomci_sbi_message_proto_rawDescData
}

var file_tr451_vomci_sbi_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tr451_vomci_sbi_message_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_tr451_vomci_sbi_message_proto_goTypes = []any{
	(VomciError_VomciErrorCode)(0), // 0: tr451_vomci_sbi_message.v1.VomciError.VomciErrorCode
	(*Hello)(nil),                  // 1: tr451_vomci_sbi_message.v1.Hello
	(*HelloVomciRequest)(nil),      // 2: tr451_vomci_sbi_message.v1.HelloVomciRequest
	(*HelloVomciResponse)(nil),     // 3: tr451_vomci_sbi_message.v1.HelloVomciResponse
	(*VomciMessage)(nil),           // 4: tr451_vomci_sbi_message.v1.VomciMessage
	(*VomciError)(nil),             // 5: tr451_vomci_sbi_message.v1.VomciError
	(*OnuHeader)(nil),              // 6: tr451_vomci_sbi_message.v1.OnuHeader
	(*OmciMsgRetrans)(nil),         // 7: tr451_vomci_sbi_message.v1.OmciMsgRetrans
	(*MessageInfo)(nil),            // 8: tr451_vomci_sbi_message.v1.MessageInfo
	(*OmciPacket)(nil),             // 9: tr451_vomci_sbi_message.v1.OmciPacket
	(*OltInfoMessage)(nil),         // 10: tr451_vomci_sbi_message.v1.OltInfoMessage
	(*OltOnuInfoReq)(nil),          // 11: tr451_vomci_sbi_message.v1.OltOnuInfoReq
	(*OltOnuInfoRsp)(nil),          // 12: tr451_vomci_sbi_message.v1.OltOnuInfoRsp
}
var file_tr451_vomci_sbi_message_proto_depIdxs = []int32{
	1,  // 0: tr451_vomci_sbi_message.v1.HelloVomciRequest.local_endpoint_hello:type_name -> tr451_vomci_sbi_message.v1.Hello
	1,  // 1: tr451_vomci_sbi_message.v1.HelloVomciResponse.remote_endpoint_hello:type_name -> tr451_vomci_sbi_message.v1.Hello
	5,  // 2: tr451_vomci_sbi_message.v1.VomciMessage.error_msg:type_name -> tr451_vomci_sbi_message.v1.VomciError
	9,  // 3: tr451_vomci_sbi_message.v1.VomciMessage.omci_packet_msg:type_name -> tr451_vomci_sbi_message.v1.OmciPacket
	9,  // 4: tr451_vomci_sbi_message.v1.VomciMessage.tod_packet_msg:type_name -> tr451_vomci_sbi_message.v1.OmciPacket
	10, // 5: tr451_vomci_sbi_message.v1.VomciMessage.olt_info_msg:type_name -> tr451_vomci_sbi_message.v1.OltInfoMessage
	0,  // 6: tr451_vomci_sbi_message.v1.VomciError.error_code:type_name -> tr451_vomci_sbi_message.v1.VomciError.VomciErrorCode
	7,  // 7: tr451_vomci_sbi_message.v1.MessageInfo.omci_msg_retrans:type_name -> tr451_vomci_sbi_message.v1.OmciMsgRetrans
	6,  // 8: tr451_vomci_sbi_message.v1.OmciPacket.header:type_name -> tr451_vomci_sbi_message.v1.OnuHeader
	8,  // 9: tr451_vomci_sbi_message.v1.OmciPacket.msg_info:type_name -> tr451_vomci_sbi_message.v1.MessageInfo
	11, // 10: tr451_vomci_sbi_message.v1.OltInfoMessage.olt_onu_info_req:type_name -> tr451_vomci_sbi_message.v1.OltOnuInfoReq
	12, // 11: tr451_vomci_sbi_message.v1.OltInfoMessage.olt_onu_info_rsp:type_name -> tr451_vomci_sbi_message.v1.OltOnuInfoRsp
	6,  // 12: tr451_vomci_sbi_message.v1.OltOnuInfoReq.header:type_name -> tr451_vomci_sbi_message.v1.OnuHeader
	6,  // 13: tr451_vomci_sbi_message.v1.OltOnuInfoRsp.header:type_name -> tr451_vomci_sbi_message.v1.OnuHeader
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_tr451_vomci_sbi_message_proto_init() }
func file_tr451_vomci_sbi_message_proto_init() {
	if File_tr451_vomci_sbi_message_proto != nil {
		return
	}
	file_tr451_vomci_sbi_message_proto_msgTypes[3].OneofWrappers = []any{
		(*VomciMessage_ErrorMsg)(nil),
		(*VomciMessage_OmciPacketMsg)(nil),
		(*VomciMessage_TodPacketMsg)(nil),
		(*VomciMessage_OltInfoMsg)(nil),
	}
	file_tr451_vomci_sbi_message_proto_msgTypes[9].OneofWrappers = []any{
		(*OltInfoMessage_OltOnuInfoReq)(nil),
		(*OltInfoMessage_OltOnuInfoRsp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tr451_vomci_sbi_message_proto_rawDesc), len(file_tr451_vomci_sbi_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tr451_vomci_sbi_message_proto_goTypes,
		DependencyIndexes: file_tr451_vomci_sbi_message_proto_depIdxs,
		EnumInfos:         file_tr451_vomci_sbi_message_proto_enumTypes,
		MessageInfos:      file_tr451_vomci_sbi_message_proto_msgTypes,
	}.Build()
	File_tr451_vomci_sbi_message_proto = out.File
	file_tr451_vomci_sbi_message_proto_goTypes = nil
	file_tr451_vomci_sbi_message_proto_depIdxs = nil
}
