// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: tr451_vomci_nbi_service.proto

//**************************************************************************
// TR-451 vOMCI NBI Service Protocol Buffer Schema
//
//  Copyright (c) 2021, Broadband Forum
//
//  Redistribution and use in source and binary forms, with or
//   without modification, are permitted provided that the following
//   conditions are met:
//
//   1. Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//
//   2. Redistributions in binary form must reproduce the above
//      copyright notice, this list of conditions and the following
//      disclaimer in the documentation and/or other materials
//      provided with the distribution.
//
//   3. Neither the name of the copyright holder nor the names of its
//      contributors may be used to endorse or promote products
//      derived from this software without specific prior written
//      permission.
//
//   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
//   CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
//   INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
//   DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
//   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
//   NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
//   CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
//   STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
//   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
//   ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
//   The above license is used as a license under copyright only.
//   Please reference the Forum IPR Policy for patent licensing terms
//   <https://www.broadband-forum.org/ipr-policy>.
//
//   Any moral rights which are necessary to exercise under the above
//   license grant are also deemed granted under this license.
//
// | Version           | Name                   | Date       |
// | TR-451 1.0.0      | vOMCI Specification    | TBD, 2021  |
//
// BBF software release registry: http://www.broadband-forum.org/software
//**************************************************************************

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VomciMessageNbi_Hello_FullMethodName                 = "/tr451_vomci_nbi_service.v1.VomciMessageNbi/Hello"
	VomciMessageNbi_GetData_FullMethodName               = "/tr451_vomci_nbi_service.v1.VomciMessageNbi/GetData"
	VomciMessageNbi_ReplaceConfig_FullMethodName         = "/tr451_vomci_nbi_service.v1.VomciMessageNbi/ReplaceConfig"
	VomciMessageNbi_UpdateConfigReplica_FullMethodName   = "/tr451_vomci_nbi_service.v1.VomciMessageNbi/UpdateConfigReplica"
	VomciMessageNbi_UpdateConfigInstance_FullMethodName  = "/tr451_vomci_nbi_service.v1.VomciMessageNbi/UpdateConfigInstance"
	VomciMessageNbi_RPC_FullMethodName                   = "/tr451_vomci_nbi_service.v1.VomciMessageNbi/RPC"
	VomciMessageNbi_Action_FullMethodName                = "/tr451_vomci_nbi_service.v1.VomciMessageNbi/Action"
	VomciMessageNbi_ListenForNotification_FullMethodName = "/tr451_vomci_nbi_service.v1.VomciMessageNbi/ListenForNotification"
)

// VomciMessageNbiClient is the client API for VomciMessageNbi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VomciMessageNbiClient interface {
	Hello(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*Msg, error)
	GetData(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*Msg, error)
	ReplaceConfig(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*Msg, error)
	UpdateConfigReplica(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*Msg, error)
	UpdateConfigInstance(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*Msg, error)
	RPC(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*Msg, error)
	Action(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*Msg, error)
	ListenForNotification(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Msg], error)
}

type vomciMessageNbiClient struct {
	cc grpc.ClientConnInterface
}

func NewVomciMessageNbiClient(cc grpc.ClientConnInterface) VomciMessageNbiClient {
	return &vomciMessageNbiClient{cc}
}

func (c *vomciMessageNbiClient) Hello(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*Msg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Msg)
	err := c.cc.Invoke(ctx, VomciMessageNbi_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vomciMessageNbiClient) GetData(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*Msg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Msg)
	err := c.cc.Invoke(ctx, VomciMessageNbi_GetData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vomciMessageNbiClient) ReplaceConfig(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*Msg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Msg)
	err := c.cc.Invoke(ctx, VomciMessageNbi_ReplaceConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vomciMessageNbiClient) UpdateConfigReplica(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*Msg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Msg)
	err := c.cc.Invoke(ctx, VomciMessageNbi_UpdateConfigReplica_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vomciMessageNbiClient) UpdateConfigInstance(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*Msg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Msg)
	err := c.cc.Invoke(ctx, VomciMessageNbi_UpdateConfigInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vomciMessageNbiClient) RPC(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*Msg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Msg)
	err := c.cc.Invoke(ctx, VomciMessageNbi_RPC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vomciMessageNbiClient) Action(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*Msg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Msg)
	err := c.cc.Invoke(ctx, VomciMessageNbi_Action_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vomciMessageNbiClient) ListenForNotification(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Msg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VomciMessageNbi_ServiceDesc.Streams[0], VomciMessageNbi_ListenForNotification_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, Msg]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VomciMessageNbi_ListenForNotificationClient = grpc.ServerStreamingClient[Msg]

// VomciMessageNbiServer is the server API for VomciMessageNbi service.
// All implementations must embed UnimplementedVomciMessageNbiServer
// for forward compatibility.
type VomciMessageNbiServer interface {
	Hello(context.Context, *Msg) (*Msg, error)
	GetData(context.Context, *Msg) (*Msg, error)
	ReplaceConfig(context.Context, *Msg) (*Msg, error)
	UpdateConfigReplica(context.Context, *Msg) (*Msg, error)
	UpdateConfigInstance(context.Context, *Msg) (*Msg, error)
	RPC(context.Context, *Msg) (*Msg, error)
	Action(context.Context, *Msg) (*Msg, error)
	ListenForNotification(*emptypb.Empty, grpc.ServerStreamingServer[Msg]) error
	mustEmbedUnimplementedVomciMessageNbiServer()
}

// UnimplementedVomciMessageNbiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVomciMessageNbiServer struct{}

func (UnimplementedVomciMessageNbiServer) Hello(context.Context, *Msg) (*Msg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedVomciMessageNbiServer) GetData(context.Context, *Msg) (*Msg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetData not implemented")
}
func (UnimplementedVomciMessageNbiServer) ReplaceConfig(context.Context, *Msg) (*Msg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplaceConfig not implemented")
}
func (UnimplementedVomciMessageNbiServer) UpdateConfigReplica(context.Context, *Msg) (*Msg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfigReplica not implemented")
}
func (UnimplementedVomciMessageNbiServer) UpdateConfigInstance(context.Context, *Msg) (*Msg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfigInstance not implemented")
}
func (UnimplementedVomciMessageNbiServer) RPC(context.Context, *Msg) (*Msg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPC not implemented")
}
func (UnimplementedVomciMessageNbiServer) Action(context.Context, *Msg) (*Msg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Action not implemented")
}
func (UnimplementedVomciMessageNbiServer) ListenForNotification(*emptypb.Empty, grpc.ServerStreamingServer[Msg]) error {
	return status.Errorf(codes.Unimplemented, "method ListenForNotification not implemented")
}
func (UnimplementedVomciMessageNbiServer) mustEmbedUnimplementedVomciMessageNbiServer() {}
func (UnimplementedVomciMessageNbiServer) testEmbeddedByValue()                         {}

// UnsafeVomciMessageNbiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VomciMessageNbiServer will
// result in compilation errors.
type UnsafeVomciMessageNbiServer interface {
	mustEmbedUnimplementedVomciMessageNbiServer()
}

func RegisterVomciMessageNbiServer(s grpc.ServiceRegistrar, srv VomciMessageNbiServer) {
	// If the following call pancis, it indicates UnimplementedVomciMessageNbiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VomciMessageNbi_ServiceDesc, srv)
}

func _VomciMessageNbi_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Msg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VomciMessageNbiServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VomciMessageNbi_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VomciMessageNbiServer).Hello(ctx, req.(*Msg))
	}
	return interceptor(ctx, in, info, handler)
}

func _VomciMessageNbi_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Msg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VomciMessageNbiServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VomciMessageNbi_GetData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VomciMessageNbiServer).GetData(ctx, req.(*Msg))
	}
	return interceptor(ctx, in, info, handler)
}

func _VomciMessageNbi_ReplaceConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Msg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VomciMessageNbiServer).ReplaceConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VomciMessageNbi_ReplaceConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VomciMessageNbiServer).ReplaceConfig(ctx, req.(*Msg))
	}
	return interceptor(ctx, in, info, handler)
}

func _VomciMessageNbi_UpdateConfigReplica_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Msg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VomciMessageNbiServer).UpdateConfigReplica(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VomciMessageNbi_UpdateConfigReplica_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VomciMessageNbiServer).UpdateConfigReplica(ctx, req.(*Msg))
	}
	return interceptor(ctx, in, info, handler)
}

func _VomciMessageNbi_UpdateConfigInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Msg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VomciMessageNbiServer).UpdateConfigInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VomciMessageNbi_UpdateConfigInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VomciMessageNbiServer).UpdateConfigInstance(ctx, req.(*Msg))
	}
	return interceptor(ctx, in, info, handler)
}

func _VomciMessageNbi_RPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Msg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VomciMessageNbiServer).RPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VomciMessageNbi_RPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VomciMessageNbiServer).RPC(ctx, req.(*Msg))
	}
	return interceptor(ctx, in, info, handler)
}

func _VomciMessageNbi_Action_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Msg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VomciMessageNbiServer).Action(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VomciMessageNbi_Action_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VomciMessageNbiServer).Action(ctx, req.(*Msg))
	}
	return interceptor(ctx, in, info, handler)
}

func _VomciMessageNbi_ListenForNotification_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VomciMessageNbiServer).ListenForNotification(m, &grpc.GenericServerStream[emptypb.Empty, Msg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VomciMessageNbi_ListenForNotificationServer = grpc.ServerStreamingServer[Msg]

// VomciMessageNbi_ServiceDesc is the grpc.ServiceDesc for VomciMessageNbi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VomciMessageNbi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tr451_vomci_nbi_service.v1.VomciMessageNbi",
	HandlerType: (*VomciMessageNbiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _VomciMessageNbi_Hello_Handler,
		},
		{
			MethodName: "GetData",
			Handler:    _VomciMessageNbi_GetData_Handler,
		},
		{
			MethodName: "ReplaceConfig",
			Handler:    _VomciMessageNbi_ReplaceConfig_Handler,
		},
		{
			MethodName: "UpdateConfigReplica",
			Handler:    _VomciMessageNbi_UpdateConfigReplica_Handler,
		},
		{
			MethodName: "UpdateConfigInstance",
			Handler:    _VomciMessageNbi_UpdateConfigInstance_Handler,
		},
		{
			MethodName: "RPC",
			Handler:    _VomciMessageNbi_RPC_Handler,
		},
		{
			MethodName: "Action",
			Handler:    _VomciMessageNbi_Action_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListenForNotification",
			Handler:       _VomciMessageNbi_ListenForNotification_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tr451_vomci_nbi_service.proto",
}
